# Generated by Django 4.0.1 on 2022-03-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('id',)},
        ),
    ]
