# Generated by Django 4.0.1 on 2022-03-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
