# Generated by Django 4.0.1 on 2022-03-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_tweetlike_tweet_likes_tweet_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.tweet'),
        ),
    ]
